# Generated by Django 5.0.1 on 2026-03-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_procedure_options_procedure_metadata_and_more'),
        ('hl7_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hl7message',
            new_name='hl7_core_hl_directi_08cb01_idx',
            old_name='hl7_core_hl_directi_81d262_idx',
        ),
        migrations.RenameIndex(
            model_name='hl7message',
            new_name='hl7_core_hl_message_824681_idx',
            old_name='hl7_core_hl_message_357be5_idx',
        ),
        migrations.RenameIndex(
            model_name='hl7message',
            new_name='hl7_core_hl_exam_id_b0f32e_idx',
            old_name='hl7_core_hl_exam_id_5410dc_idx',
        ),
        migrations.AlterField(
            model_name='hl7configuration',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hl7_configurations', to='core.facility'),
        ),
        migrations.AlterUniqueTogether(
            name='hl7configuration',
            unique_together={('facility',)},
        ),
    ]
