# Generated by Django 5.0.1 on 2026-02-02 08:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_procedure_options_procedure_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted At')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Protocol Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Protocol Name')),
                ('body_part', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Body Part')),
                ('body_region', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Body Region')),
                ('laterality', models.CharField(blank=True, max_length=20, verbose_name='Laterality')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Is Default')),
                ('priority', models.PositiveIntegerField(db_index=True, default=50, verbose_name='Priority')),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Usage Count')),
                ('requires_contrast', models.BooleanField(default=False, verbose_name='Requires Contrast')),
                ('contrast_type', models.CharField(blank=True, max_length=120, verbose_name='Contrast Type')),
                ('contrast_phase', models.CharField(blank=True, max_length=120, verbose_name='Contrast Phase')),
                ('contrast_notes', models.TextField(blank=True, verbose_name='Contrast Notes')),
                ('indications', models.TextField(blank=True, verbose_name='Indications')),
                ('patient_prep', models.TextField(blank=True, verbose_name='Patient Preparation')),
                ('contraindications', models.TextField(blank=True, verbose_name='Contraindications')),
                ('safety_notes', models.TextField(blank=True, verbose_name='Safety Notes')),
                ('post_processing', models.TextField(blank=True, verbose_name='Post Processing')),
                ('general_notes', models.TextField(blank=True, verbose_name='General Notes')),
                ('clinical_keywords', models.JSONField(blank=True, default=list, verbose_name='Clinical Keywords')),
                ('technical_parameters', models.JSONField(blank=True, default=dict, verbose_name='Technical Parameters')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='If set, protocol is facility-specific. If empty, protocol is global.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocol_templates', to='core.facility')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_templates', to='core.modality')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocol_templates', to='core.procedure')),
            ],
            options={
                'verbose_name': 'Protocol Template',
                'verbose_name_plural': 'Protocol Templates',
                'ordering': ['modality__code', 'priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolSuggestionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_protocols', models.JSONField(default=list, verbose_name='Suggested Protocols')),
                ('clinical_context', models.JSONField(default=dict, verbose_name='Clinical Context')),
                ('selected_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Selected Rank')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='Selected At')),
                ('suggestion_algorithm_version', models.CharField(default='1.0', max_length=20, verbose_name='Algorithm Version')),
                ('suggestion_generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Suggestion Generated At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_suggestion_logs', to='core.exam')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_suggestion_logs', to=settings.AUTH_USER_MODEL)),
                ('selected_protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_logs', to='protocols.protocoltemplate')),
                ('top_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_suggestion_logs', to='protocols.protocoltemplate')),
            ],
            options={
                'verbose_name': 'Protocol Suggestion Log',
                'verbose_name_plural': 'Protocol Suggestion Logs',
                'ordering': ['-suggestion_generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ser', models.PositiveIntegerField(verbose_name='SER (Sequence #)')),
                ('coil', models.CharField(blank=True, max_length=120, verbose_name='COIL')),
                ('phase_array', models.CharField(blank=True, max_length=120, verbose_name='PH. ARRAY')),
                ('scan_plane', models.CharField(max_length=80, verbose_name='SCAN PLANE')),
                ('pulse_sequence', models.CharField(max_length=120, verbose_name='PULSE SEQ.')),
                ('options', models.CharField(blank=True, max_length=200, verbose_name='OPTIONS')),
                ('comments', models.TextField(blank=True, verbose_name='COMMENTS')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='protocols.protocoltemplate')),
            ],
            options={
                'verbose_name': 'Protocol Sequence',
                'verbose_name_plural': 'Protocol Sequences',
                'ordering': ['protocol', 'ser'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Assigned At')),
                ('assignment_method', models.CharField(choices=[('AI', 'AI Suggested'), ('MANUAL', 'Manual'), ('OVERRIDE', 'Override AI')], db_index=True, default='MANUAL', max_length=15, verbose_name='Assignment Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15, verbose_name='Status')),
                ('radiologist_note', models.TextField(blank=True, verbose_name='Radiologist Note')),
                ('technologist_note', models.TextField(blank=True, verbose_name='Technologist Note')),
                ('assignment_notes', models.TextField(blank=True, verbose_name='Assignment Notes')),
                ('is_modified', models.BooleanField(default=False, verbose_name='Is Modified')),
                ('modifications', models.JSONField(blank=True, default=dict, verbose_name='Modifications')),
                ('modification_notes', models.TextField(blank=True, verbose_name='Modification Notes')),
                ('was_suggested', models.BooleanField(default=False, verbose_name='Was Suggested')),
                ('suggestion_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Suggestion Rank')),
                ('suggestion_score', models.FloatField(blank=True, null=True, verbose_name='Suggestion Score')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('technologist_notified', models.BooleanField(default=False, verbose_name='Technologist Notified')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notification Sent At')),
                ('hl7_sent', models.BooleanField(default=False, verbose_name='HL7 Sent')),
                ('hl7_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='HL7 Sent At')),
                ('hl7_message_id', models.CharField(blank=True, max_length=64, verbose_name='HL7 Message ID')),
                ('sent_to_ris_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent to RIS At')),
                ('ris_ack_at', models.DateTimeField(blank=True, null=True, verbose_name='RIS Acknowledged At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_protocols', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_assignments', to=settings.AUTH_USER_MODEL)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_assignment', to='core.exam')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='protocols.protocoltemplate')),
            ],
            options={
                'verbose_name': 'Protocol Assignment',
                'verbose_name_plural': 'Protocol Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologistPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_part', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Body Part')),
                ('clinical_pattern', models.JSONField(blank=True, default=dict, verbose_name='Clinical Pattern')),
                ('confidence_score', models.FloatField(db_index=True, default=0.5, verbose_name='Confidence Score')),
                ('selection_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Selection Count')),
                ('last_selected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last Selected At')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologist_preferences', to='core.facility')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiologist_preferences', to='core.modality')),
                ('preferred_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by_radiologists', to='protocols.protocoltemplate')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiologist_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radiologist Preference',
                'verbose_name_plural': 'Radiologist Preferences',
                'ordering': ['-confidence_score', '-last_selected_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted At')),
                ('author_role', models.CharField(blank=True, max_length=40, verbose_name='Author Role')),
                ('message', models.TextField(verbose_name='Message')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='protocols.protocolassignment')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_comments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocol Comment',
                'verbose_name_plural': 'Protocol Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='protocols_p_created_5bf7ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='protocoltemplate',
            index=models.Index(fields=['modality', 'is_active', 'priority'], name='protocols_p_modalit_891811_idx'),
        ),
        migrations.AddIndex(
            model_name='protocoltemplate',
            index=models.Index(fields=['code', 'is_active'], name='protocols_p_code_cf46c6_idx'),
        ),
        migrations.AddIndex(
            model_name='protocoltemplate',
            index=models.Index(fields=['facility', 'is_active'], name='protocols_p_facilit_b9ddf7_idx'),
        ),
        migrations.AddIndex(
            model_name='protocoltemplate',
            index=models.Index(fields=['body_part'], name='protocols_p_body_pa_a832fc_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsuggestionlog',
            index=models.Index(fields=['exam', '-suggestion_generated_at'], name='protocols_p_exam_id_7933df_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolsuggestionlog',
            index=models.Index(fields=['radiologist', '-suggestion_generated_at'], name='protocols_p_radiolo_cd9f26_idx'),
        ),
        migrations.AddConstraint(
            model_name='protocolsequence',
            constraint=models.UniqueConstraint(fields=('protocol', 'ser'), name='uq_protocol_ser'),
        ),
        migrations.AddIndex(
            model_name='protocolassignment',
            index=models.Index(fields=['assignment_method', 'status', '-created_at'], name='protocols_p_assignm_30e84e_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolassignment',
            index=models.Index(fields=['assigned_at'], name='protocols_p_assigne_d0b831_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolassignment',
            index=models.Index(fields=['was_suggested'], name='protocols_p_was_sug_1e361a_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologistpreference',
            index=models.Index(fields=['radiologist', 'modality'], name='protocols_r_radiolo_724b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologistpreference',
            index=models.Index(fields=['radiologist', 'modality', 'body_part'], name='protocols_r_radiolo_344589_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologistpreference',
            index=models.Index(fields=['preferred_protocol'], name='protocols_r_preferr_4e9782_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologistpreference',
            index=models.Index(fields=['facility'], name='protocols_r_facilit_74f755_idx'),
        ),
        migrations.AddConstraint(
            model_name='radiologistpreference',
            constraint=models.UniqueConstraint(fields=('radiologist', 'modality', 'body_part', 'preferred_protocol', 'facility'), name='uq_radiologist_pref_context'),
        ),
    ]
