# Generated by Django 5.0.1 on 2026-01-23 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted At')),
                ('accession_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Accession Number')),
                ('order_id', models.CharField(db_index=True, max_length=100, verbose_name='Order ID')),
                ('mrn', models.CharField(db_index=True, max_length=100, verbose_name='MRN')),
                ('procedure_code', models.CharField(blank=True, max_length=50, verbose_name='Procedure Code')),
                ('procedure_name', models.CharField(max_length=200, verbose_name='Procedure Name')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Patient Name')),
                ('patient_dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('patient_gender', models.CharField(blank=True, max_length=1, verbose_name='Gender')),
                ('clinical_history', models.TextField(blank=True, verbose_name='Clinical History')),
                ('reason_for_exam', models.TextField(blank=True, verbose_name='Reason for Exam')),
                ('scheduled_datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled DateTime')),
                ('exam_datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Exam DateTime')),
                ('ordering_provider', models.CharField(blank=True, max_length=200, verbose_name='Ordering Provider')),
                ('technologist', models.CharField(blank=True, max_length=200, verbose_name='Technologist')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Patient Arrived'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('hl7_message_control_id', models.CharField(blank=True, max_length=100, verbose_name='HL7 Message Control ID')),
                ('raw_hl7_message', models.TextField(blank=True, verbose_name='Raw HL7 Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_datetime', '-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Facility Code')),
                ('name', models.CharField(max_length=200, verbose_name='Facility Name')),
                ('hl7_facility_id', models.CharField(blank=True, max_length=100, verbose_name='HL7 Facility ID')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Contact Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Modality Code')),
                ('name', models.CharField(max_length=100, verbose_name='Modality Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('requires_qc', models.BooleanField(default=True, verbose_name='Requires QC')),
                ('qc_checklist_template', models.JSONField(blank=True, default=dict, verbose_name='QC Checklist Template')),
            ],
            options={
                'verbose_name': 'Modality',
                'verbose_name_plural': 'Modalities',
                'ordering': ['code'],
            },
        ),
    ]
