# Generated by Django 5.0.1 on 2026-01-23 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='core.facility'),
        ),
        migrations.AddField(
            model_name='exam',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='core.modality'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['facility', 'status', '-exam_datetime'], name='core_exam_facilit_11f3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['modality', 'status'], name='core_exam_modalit_458d05_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['mrn', '-exam_datetime'], name='core_exam_mrn_e3e560_idx'),
        ),
    ]
