# Generated by Django 5.0.1 on 2026-01-31 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Procedure Code')),
                ('name', models.CharField(max_length=255, verbose_name='Procedure Name')),
                ('body_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Body Region')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='core.modality')),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
                'ordering': ['code'],
            },
        ),
    ]
