# Generated by Django 5.0.1 on 2026-02-01 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_procedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['modality__code', 'code'], 'verbose_name': 'Procedure', 'verbose_name_plural': 'Procedures'},
        ),
        migrations.AddField(
            model_name='procedure',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='body_region',
            field=models.CharField(choices=[('Head', 'Head'), ('Neck', 'Neck'), ('Chest', 'Chest'), ('Abdomen', 'Abdomen'), ('Pelvis', 'Pelvis'), ('Spine', 'Spine'), ('Upper Extremity', 'Upper Extremity'), ('Lower Extremity', 'Lower Extremity'), ('Breast', 'Breast'), ('Multi Area', 'Multi Area'), ('Body', 'Body'), ('Nonspecific', 'Nonspecific')], db_index=True, default='Nonspecific', max_length=40, verbose_name='Body Region'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['modality', 'body_region', 'is_active'], name='core_proced_modalit_b68677_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['code', 'is_active'], name='core_proced_code_03c86d_idx'),
        ),
    ]
