# Generated by Django 5.0.1 on 2026-03-04 23:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_procedure_options_procedure_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrastUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pec_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='PEC Number')),
                ('contrast_name', models.CharField(max_length=120, verbose_name='Contrast Name')),
                ('concentration_mg_ml', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Concentration (mg/mL)')),
                ('volume_ml', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Volume (mL)')),
                ('total_mg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Total (mg)')),
                ('injection_rate_ml_s', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Injection Rate (mL/s)')),
                ('route', models.CharField(choices=[('IV', 'IV'), ('ORAL', 'Oral')], default='IV', max_length=10, verbose_name='Route')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Lot Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('patient_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Patient Weight (kg)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrast_usages', to='core.exam')),
            ],
            options={
                'verbose_name': 'Contrast Usage',
                'verbose_name_plural': 'Contrast Usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exam', '-created_at'], name='core_contrast_exam_created_idx'), models.Index(fields=['pec_number', '-created_at'], name='core_contrast_pec_created_idx'), models.Index(fields=['contrast_name', '-created_at'], name='core_contrast_name_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pec_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='PEC Number')),
                ('material_name', models.CharField(max_length=120, verbose_name='Material Name')),
                ('unit', models.CharField(choices=[('ml', 'mL'), ('mg', 'mg'), ('cc', 'cc')], default='ml', max_length=10, verbose_name='Unit')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='core.exam')),
            ],
            options={
                'verbose_name': 'Material Usage',
                'verbose_name_plural': 'Material Usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exam', '-created_at'], name='core_material_exam_created_idx'), models.Index(fields=['pec_number', '-created_at'], name='core_material_pec_created_idx'), models.Index(fields=['material_name', '-created_at'], name='core_material_name_created_idx')],
            },
        ),
    ]
