# Generated by Django 5.0.1 on 2026-03-04 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contrastusage_materialusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCatalog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Material Name')),
                ('category', models.CharField(choices=[('CONTRAST', 'Contrast'), ('DISPOSABLE', 'Disposable'), ('OTHER', 'Other')], db_index=True, default='DISPOSABLE', max_length=20, verbose_name='Category')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Material Catalog Item',
                'verbose_name_plural': 'Material Catalog Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMeasurement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Measurement Code')),
                ('label', models.CharField(max_length=80, verbose_name='Measurement Label')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Material Measurement',
                'verbose_name_plural': 'Material Measurements',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='material_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Material Name'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='unit',
            field=models.CharField(blank=True, max_length=40, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='material_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='core.materialcatalog'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='default_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.materialmeasurement'),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='core.materialmeasurement'),
        ),
    ]
