# Generated by Django 5.0.1 on 2026-03-05 02:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_materialcatalog_materialmeasurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureMaterialBundle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_code', models.CharField(db_index=True, max_length=50, verbose_name='Procedure Code')),
                ('procedure_name', models.CharField(blank=True, max_length=255, verbose_name='Procedure Name')),
                ('modality_scope', models.CharField(blank=True, max_length=120, verbose_name='Modality Scope')),
                ('rules_notes', models.TextField(blank=True, verbose_name='Rules / Notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Procedure Material Bundle',
                'verbose_name_plural': 'Procedure Material Bundles',
                'ordering': ['procedure_code'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureMaterialBundleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_code', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Material Code')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Quantity')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=10, verbose_name='Sort Order')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Is Optional')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Procedure Material Bundle Item',
                'verbose_name_plural': 'Procedure Material Bundle Items',
                'ordering': ['bundle', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='billable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Billable'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='billing_ref_example',
            field=models.CharField(blank=True, max_length=80, verbose_name='Billing Ref Example'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='charge_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Charge Code'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='cost_center_only',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cost Center Only'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='default_price_sar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Default Price (SAR)'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='material_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True, verbose_name='Material Code'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='modality_scope',
            field=models.CharField(blank=True, max_length=120, verbose_name='Modality Scope'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='nphies_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='NPHIES Code'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='pack_size',
            field=models.CharField(blank=True, max_length=40, verbose_name='Pack Size'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='procedure_mapping_tags',
            field=models.TextField(blank=True, verbose_name='Procedure Mapping Tags'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Reorder Level'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='typical_cost_sar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Typical Cost (SAR)'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='materialcatalog',
            name='category',
            field=models.CharField(db_index=True, default='DISPOSABLE', max_length=80, verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='materialcatalog',
            index=models.Index(fields=['category', 'is_active'], name='core_materi_categor_14169c_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcatalog',
            index=models.Index(fields=['material_code', 'is_active'], name='core_materi_materia_c3a6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcatalog',
            index=models.Index(fields=['modality_scope', 'is_active'], name='core_materi_modalit_5adafb_idx'),
        ),
        migrations.AddField(
            model_name='procedurematerialbundle',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_bundles', to='core.procedure'),
        ),
        migrations.AddField(
            model_name='procedurematerialbundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.procedurematerialbundle'),
        ),
        migrations.AddField(
            model_name='procedurematerialbundleitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_items', to='core.materialcatalog'),
        ),
        migrations.AddIndex(
            model_name='procedurematerialbundle',
            index=models.Index(fields=['procedure_code', 'is_active'], name='core_proced_procedu_4e9a21_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurematerialbundle',
            index=models.Index(fields=['modality_scope', 'is_active'], name='core_proced_modalit_136df8_idx'),
        ),
        migrations.AddConstraint(
            model_name='procedurematerialbundle',
            constraint=models.UniqueConstraint(fields=('procedure_code',), name='uq_core_proc_bundle_code'),
        ),
        migrations.AddIndex(
            model_name='procedurematerialbundleitem',
            index=models.Index(fields=['bundle', 'sort_order'], name='core_proced_bundle__d6a981_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurematerialbundleitem',
            index=models.Index(fields=['material_code'], name='core_proced_materia_8c0d6d_idx'),
        ),
    ]
