# Generated by Django 5.0.1 on 2026-03-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modality_requires_contrast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('ORDER', 'Order'), ('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Patient Arrived'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Canceled'), ('NO_SHOW', 'No Show')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='Status'),
        ),
    ]
