# Generated by Django 5.0.1 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='qc_service_desk_email',
            field=models.EmailField(blank=True, default='helpdesk@Aaml.com.sa', max_length=254, verbose_name='QC Service Desk Email'),
        ),
    ]
