# Generated by Django 5.0.1 on 2026-03-04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_procedure_options_procedure_metadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QCChecklist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80, verbose_name="Checklist Key")),
                ("label", models.CharField(max_length=200, verbose_name="Checklist Label")),
                ("help_text", models.TextField(blank=True, verbose_name="Help Text")),
                ("is_required", models.BooleanField(default=True, verbose_name="Required")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("sort_order", models.PositiveSmallIntegerField(db_index=True, default=10, verbose_name="Sort Order")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_checklists",
                        to="core.modality",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Checklist Item",
                "verbose_name_plural": "QC Checklist Items",
                "ordering": ["modality__code", "sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="QCSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("accession_number", models.CharField(db_index=True, max_length=100, verbose_name="Accession Number")),
                ("mrn", models.CharField(blank=True, db_index=True, max_length=100, verbose_name="MRN")),
                ("modality_code", models.CharField(blank=True, max_length=16, verbose_name="Modality")),
                ("study_name", models.CharField(blank=True, max_length=255, verbose_name="Study")),
                ("checklist_state", models.JSONField(blank=True, default=dict, verbose_name="Checklist State")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Session Status",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Submitted At")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_sessions",
                        to="core.exam",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Session",
                "verbose_name_plural": "QC Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QCImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("accession_number", models.CharField(db_index=True, max_length=100, verbose_name="Accession Number")),
                ("image", models.FileField(upload_to="evidence/qc/%Y/%m/%d/", verbose_name="PNG Evidence")),
                ("original_filename", models.CharField(blank=True, max_length=255, verbose_name="Original Filename")),
                ("pacs_link", models.CharField(blank=True, max_length=500, verbose_name="PACS Link")),
                ("width", models.PositiveIntegerField(blank=True, null=True, verbose_name="Width")),
                ("height", models.PositiveIntegerField(blank=True, null=True, verbose_name="Height")),
                ("capture_order", models.PositiveIntegerField(db_index=True, default=1, verbose_name="Capture Order")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="qc.qcsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Image",
                "verbose_name_plural": "QC Images",
                "ordering": ["session", "capture_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QCAnnotation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tool",
                    models.CharField(
                        choices=[
                            ("ARROW", "Arrow"),
                            ("CIRCLE", "Circle"),
                            ("FREE_DRAW", "Free Draw"),
                            ("TEXT", "Text"),
                        ],
                        max_length=20,
                        verbose_name="Tool",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Payload")),
                ("text_note", models.TextField(blank=True, verbose_name="Text Note")),
                ("color", models.CharField(blank=True, max_length=16, verbose_name="Color")),
                ("stroke_width", models.PositiveSmallIntegerField(default=2, verbose_name="Stroke Width")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="qc.qcimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Annotation",
                "verbose_name_plural": "QC Annotations",
                "ordering": ["image", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QCResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        db_index=True,
                        max_length=16,
                        verbose_name="Decision",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Reviewed At")),
                ("checklist_results", models.JSONField(blank=True, default=dict, verbose_name="Checklist Results")),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_results",
                        to="core.exam",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="qc.qcsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Result",
                "verbose_name_plural": "QC Results",
                "ordering": ["-reviewed_at", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="qcchecklist",
            constraint=models.UniqueConstraint(fields=("modality", "key"), name="uq_qc_checklist_modality_key"),
        ),
        migrations.AddIndex(
            model_name="qcchecklist",
            index=models.Index(fields=["modality", "is_active", "sort_order"], name="qc_check_mod_act_sort_idx"),
        ),
        migrations.AddIndex(
            model_name="qcsession",
            index=models.Index(fields=["exam", "-created_at"], name="qc_session_exam_created_idx"),
        ),
        migrations.AddIndex(
            model_name="qcsession",
            index=models.Index(fields=["reviewer", "-created_at"], name="qc_session_rev_created_idx"),
        ),
        migrations.AddIndex(
            model_name="qcsession",
            index=models.Index(fields=["accession_number", "-created_at"], name="qc_session_acc_created_idx"),
        ),
        migrations.AddIndex(
            model_name="qcsession",
            index=models.Index(fields=["status", "-created_at"], name="qc_session_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="qcimage",
            index=models.Index(fields=["session", "capture_order"], name="qc_image_session_order_idx"),
        ),
        migrations.AddIndex(
            model_name="qcimage",
            index=models.Index(fields=["accession_number", "-created_at"], name="qc_image_acc_created_idx"),
        ),
        migrations.AddIndex(
            model_name="qcannotation",
            index=models.Index(fields=["image", "created_at"], name="qc_annot_image_created_idx"),
        ),
        migrations.AddIndex(
            model_name="qcannotation",
            index=models.Index(fields=["tool", "created_at"], name="qc_annot_tool_created_idx"),
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(fields=["exam", "-reviewed_at"], name="qc_result_exam_reviewed_idx"),
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(fields=["decision", "-reviewed_at"], name="qc_result_decision_review_idx"),
        ),
    ]
