# Generated by Django 5.0.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcsession",
            name="concern_raised",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Concern Raised"),
        ),
    ]
