# Generated by Django 5.0.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qc", "0002_qcsession_concern_raised"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qcsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("SAVED", "Saved"),
                    ("DRAFT", "Draft"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("REPLIED", "Replied"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
                verbose_name="Session Status",
            ),
        ),
    ]
