# Generated by Django 5.0.1 on 2026-03-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ['last_name', 'first_name'],
                'permissions': (
                    ('qc_view', 'Can view QC workflows'),
                    ('qc_create', 'Can create QC records'),
                    ('qc_edit', 'Can edit QC records'),
                    ('qc_approve', 'Can approve QC records'),
                    ('qc_evidence_capture', 'Can capture QC evidence'),
                    ('qc_evidence_view', 'Can view QC evidence'),
                    ('protocol_view', 'Can view protocol workflows'),
                    ('protocol_assign', 'Can assign protocols'),
                    ('protocol_edit', 'Can edit protocols'),
                    ('contrast_view', 'Can view contrast workflows'),
                    ('contrast_create', 'Can create contrast records'),
                    ('contrast_edit', 'Can edit contrast records'),
                    ('contrast_approve', 'Can approve contrast records'),
                    ('report_view', 'Can view reports'),
                    ('report_export', 'Can export reports'),
                    ('admin_access', 'Can access administrative areas'),
                    ('audit_view', 'Can view audit records'),
                ),
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
