# Generated by Django 5.0.1 on 2026-03-04 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('category', models.CharField(db_index=True, default='INFO', max_length=40, verbose_name='Category')),
                ('target_url', models.CharField(blank=True, max_length=500, verbose_name='Target URL')),
                ('email_sent', models.BooleanField(db_index=True, default=False, verbose_name='Email Sent')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='Emailed At')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Read At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='users_usern_recipie_5f60ef_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['recipient', '-created_at'], name='users_usern_recipie_ee4d38_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['category', '-created_at'], name='users_usern_categor_8a1c81_idx'),
        ),
    ]
