# Generated by Django 5.0.1 on 2026-03-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usernotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='users_usern_recipie_69d882_idx',
            old_name='users_usern_recipie_5f60ef_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='users_usern_recipie_9b8ee7_idx',
            old_name='users_usern_recipie_ee4d38_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='users_usern_categor_f0cd95_idx',
            old_name='users_usern_categor_8a1c81_idx',
        ),
    ]
