# Generated by Django 5.0.1 on 2026-03-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RADIOLOGIST', 'Radiologist'), ('TECHNOLOGIST', 'Technologist'), ('SUPERVISOR', 'Supervisor'), ('FINANCE', 'Finance'), ('ADMIN', 'Administrator'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20, verbose_name='Role'),
        ),
    ]
