# Generated by Django 5.0.1 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_body_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Head", "Head"),
                    ("Neck", "Neck"),
                    ("Chest", "Chest"),
                    ("Abdomen", "Abdomen"),
                    ("Pelvis", "Pelvis"),
                    ("Spine", "Spine"),
                    ("Upper Extremity", "Upper Extremity"),
                    ("Lower Extremity", "Lower Extremity"),
                    ("Breast", "Breast"),
                    ("Multi Area", "Multi Area"),
                    ("Body", "Body"),
                    ("Nonspecific", "Nonspecific"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Default Body Part",
            ),
        ),
    ]
