# Generated by Django 5.0.1 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_default_body_part"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="default_body_part",
        ),
        migrations.AlterField(
            model_name="user",
            name="specialty",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Default Subspecialty",
            ),
        ),
    ]
